<?php
namespace CoinPayments\Components\Payment;


class CoinPaymentsPaymenttMethod extends \ShopwarePlugin\PaymentMethods\Components\GenericPaymentMethod
{
    public function validate($paymentData)
    {
        print_r($paymentData);die();
        return parent::validate($paymentData); // TODO: Change the autogenerated stub
    }
}